{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "MenuSet",
		"Service": "/BlogMDKDemoApp/Services/openSAPNewService.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties":  {
	"BookingID": "#Control:BookingID/#Value",
	"CanteenID": "#Control:CanteenID/#Value",
	"Dessert": "#Control:Dessert/#Value",
	"MainDish": "#Control:MainDish/#Value",
	"MenuID": "#Control:MenuID/#Value",
	"Price": "#Control:Price/#Value",
	"Sides": "#Control:Sides/#Value",
	"Soup": "#Control:Soup/#Value",
	"dateOfLunch": "#Control:dateOfLunch/#Value",
	"kcalForMain": "#Control:kcalForMain/#Value",
	"veggie": "#Control:veggie/#Value"
},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/BlogMDKDemoApp/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/BlogMDKDemoApp/Actions/UpdateEntityFailureMessage.action"
}